### ISSUE TITLE
what does the hihealth_003.db contain any progress to convert that.

### ISSUE THREAD

**Issue by 1kaiser** [CTHRU/Hitrava#40]
what does the hihealth_003.db contain any progress to convert that.

**Comment by CTHRU** [comment]
I assume you are referring to the Huawei Health app database on the phone.
It will definitely contain the activity data in some form or other.
As far as I'm concerned, I don't have any plans to investigate/develop in that direction, mainly because:
- It's (probably) encrypted.
- It will require a rooted phone or emulator to access it.
- Legal use considerations.
- ...

In short, too many impediments the way I see it.
