### ISSUE TITLE
Help with web upload

### ISSUE THREAD

**Issue by FerbsTheRed** [CTHRU/Hitrava#48]
Hi,

I just tried out your web upload and it seems to load my huawei health activities up to the 15th December.  After this date the activities are shown but I cannot select them to convert.  See attached screen shot.

Please can you check if something has changed in the file format?
I just retrieved my first file today.
Many thanks, site looks good if i can get my recent data to upload.  
![HitravaWeb](https://user-images.githubusercontent.com/77881869/105576544-542c3800-5d6b-11eb-8113-3453fd55461e.PNG)

Ian

**Comment by CTHRU** [comment]
@FerbsTheRed Thank you for your interest in Hitrava Web, What you notice, is 'normal'. It's currently an alpha version and I decided to release it in trial mode only for now. This means that some of the last activities will be greyed out. It's also mentioned in the alpha software notice [here](https://cthru.hopto.org/hitrava-web-alpha/).
I'm trying to continue to work on it in my spare time, but due to personal reasons, I am currently unable to spend the necessary time. I thank you for your patience.
See also #32.
